name: Build and push image to repository
on:
  push:
    branches:
      - master
    paths:
      - release.sh
      - Dockerfile
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Authenticate with registry
        run: docker login docker.pkg.github.com -u "BigWigsMods" -p "${{ secrets.DOCKER_PASS }}"

      - name: Build and push image
        run: |
          TAG="$(date -u +%Y%m%d%H%M%S)"
          docker build . \
            -t docker.pkg.github.com/bigwigsmods/packager/packager:$TAG \
            -t docker.pkg.github.com/bigwigsmods/packager/packager:latest
          docker push docker.pkg.github.com/bigwigsmods/packager/packager:$TAG
          docker push docker.pkg.github.com/bigwigsmods/packager/packager:latest
